site_name: ScolCoin Chain Docs
site_description: ScolCoin Chain Technology Documentation
site_author: ScolCoin Chain Community

site_url: https://docs.scolcoin.com
use_directory_urls: false
theme:
  name: material

repo_name: shree
repo_url: https://github.com/scolcoin/MkDocs

nav:
  - Home: index.md
  - ScolCoin Chain:
    - Introduction: smart-chain/guides/nc-intro.md
    - Concepts:
      - Consensus: smart-chain/guides/concepts/consensus.md
      - Comparison: smart-chain/guides/general.md
      - Genesis File: smart-chain/guides/concepts/genesis.md
      - System Contract: smart-chain/guides/concepts/system-contract.md
      - Governance: smart-chain/guides/concepts/nc-gov.md
    - Ecosystem: https://github.com/scolcoin/
    - Gnosis: smart-chain/developer/gnosis.md
    - Staking:
      - Validator:
        - Overview: smart-chain/validator/overview.md
        - Validator Guides: smart-chain/validator/guideline.md
        - Validator Security: smart-chain/validator/security.md
        - Chaindata Snapshot: smart-chain/developer/snapshot.md       
        - Testnet : smart-chain/validator/testnet.md
        - Validator FAQ: faq/nc/val.md
      - Delegator Guide: smart-chain/delegator/del-guide.md
    - Cross Chain Apps: smart-chain/guides/cross-chain.md
    - ScolCoin Chain Mainnet Explorer: https://scolcoin.com/
    - ScolCoin Chain Testnet Explorer: https://testnet-explorer.scolcoin.com/
    - Wallet: smart-chain/wallet.md
  - SCOL  Developers:
    - General:
      - Create Wallet: smart-chain/developer/create-wallet.md
      - Smart Contract: https://solidity.readthedocs.io/en/v0.7.1/
      - Remix : https://remix.ethereum.org/
      - Web3JS: https://web3js.readthedocs.io/en/v1.2.11/
      - Truffle: https://www.trufflesuite.com/docs/teams/quickstart
    - Ecosystem:https://github.com/githubusername/githubrepo-develop-ecosystem
    - Deploy:
      - Remix: smart-chain/developer/deploy/remix.md
      - Truffle: smart-chain/developer/deploy/truffle.md
      - Truffle Verify: smart-chain/developer/deploy/truffle-verify.md
      - HardHat: smart-chain/developer/deploy/hardhat.md
      - HardHat Verify: smart-chain/developer/deploy/hardhat-verify.md
      - Verify Proxy Contract: smart-chain/developer/upgrade/verify-proxy.md
    - Tools:
      - Faucet: https://faucet.scolcoin.com/
      - Gas Price: https://scolcoin.com/chart/gasprice
      - Wallet Provider for DApps: smart-chain/wallet/arkane-developer.md
    - SRC20 Tokens:
      - Introduction: smart-chain/developer/SRC20.md
      - Issue Token: smart-chain/developer/issue-SRC20.md
      - Bind Token:
        - Introduction: smart-chain/developer/bind/tokens-cross-chain.md
        - Bind Token: smart-chain/developer/bind/bind-tokens.md
        - Mirror Token: smart-chain/developer/bind/mirror.md
        - Sync Supply: smart-chain/developer/bind/sync.md
      - Cross-chain Transfer: smart-chain/developer/cross-chain-transfer.md
      - Bind Token Tool:https://github.com/githubusername/githubrepo/token-bind-tool
    - Blockchain Details:
      - ScolCoin Chain Fullnode: smart-chain/developer/fullnode.md
      - Chaindata Snapshot: smart-chain/developer/snapshot.md
      - SCOL  Relayer: smart-chain/developer/nc-relayer.md
      - RPC: smart-chain/developer/rpc.md
    - Oracles:
      - Band Protocol Integration: smart-chain/developer/oracle/band.md
      - Chainlink Protocol Integration: smart-chain/developer/oracle/link.md
      - Chainlink Protocol VRF: https://docs.chain.link/docs/chainlink-vrf
    - Tutorial:
      - Deploy NFT:  smart-chain/developer/SRC721.md
      - Verify Contract on scolcoin.com: smart-chain/developer/deploy/verify.md
      - Local SCOL  Network: smart-chain/developer/deploy/local.md
      - Proxy Contract: smart-chain/developer/upgrade/proxy.md
    - BUIDL Program: https://medium.com/@scolcoin_337
  - Wallets:
    - ScolCoin Chain Wallet Support: smart-chain/wallet.md
    - ScolCoin Chain Wallet Tutorial:
      - How to create a SCOL  wallet: smart-chain/wallet/arkane.md
      - Math Wallet User Guide: smart-chain/wallet/math-resource.md
      - Staking with extension wallet: smart-chain/wallet/staking.md
      - How to install SCOL Extension Wallet Manually: smart-chain/wallet/manual.md
      - How to use ezDeFi Wallet for ScolCoin Chain: smart-chain/wallet/ezdefi.md
  - ScolCoin Chain Explorer: https://explorer.scolcoin.com/
  - ScolCoin Chain Forum: https://forum.scolcoin.com/
  - ScolCoin Chain Faucet: https://faucet.scolcoin.com/
  - The ScolCoin Chain Developer Group : https://t.me/scolcoin_foro
  - The ScolCoin Chain Telegram Group : https://t.me/scolcoin
  - Twitter: https://twitter.com/scolcoin
  - Telegram Announcement Channel English: https://t.me/ScolCoinNews
  - FAQ:
    - ScolCoin Chain FAQ:
      - General:
        - Info: faq/nc/general.md
        - ScolCoin Chain: faq/nc/bsc.md
        - Ecosystem: faq/nc/eco.md
      - Token:
        - Intro: faq/nc/token.md
        - BEPs: faq/nc/bep.md
      - Staking:
        - Validator: faq/nc/val.md
        - Delegator: faq/nc/del.md
        - Staking parameters: smart-chain/validator/Parameters.md
      - Crosschain: faq/nc/cross.md
    - More Help: resources.md
    - Contributing: CONTRIBUTING.md
